// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

namespace backend.Migrations
{
    [DbContext(typeof(TvShowsContext))]
    [Migration("20190323172329_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("backend.Models.Episode", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("TvShowid");

                    b.Property<string>("imageUrl");

                    b.Property<int>("parentId");

                    b.Property<float>("rating");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.HasIndex("TvShowid");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("backend.Models.TvShow", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("imageUrl");

                    b.Property<float>("rating");

                    b.Property<string>("title");

                    b.HasKey("id");

                    b.ToTable("Shows");
                });

            modelBuilder.Entity("backend.Models.Episode", b =>
                {
                    b.HasOne("backend.Models.TvShow")
                        .WithMany("Episodes")
                        .HasForeignKey("TvShowid");
                });
#pragma warning restore 612, 618
        }
    }
}
